/*
 * Copyright 2025, Arno Puder
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.puder.trs80.shared

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * Guards the properties the table used to get for free from being generated by a
 * parser, now that it is written out.
 */
class KeyboardMappingTest {

    @Test
    fun everyEntrySitsAtItsOwnValue() {
        // `value` is the index, and `Key.TK_*` indexes in. If these ever drift,
        // every on-screen key sends the wrong code.
        KeyboardMapping.entries.forEachIndexed { index, entry ->
            assertEquals(index, entry.value, "'${entry.name}' is at $index.")
        }
    }

    @Test
    fun namesAreUnique() {
        // byName() and injectKey() look entries up this way, so a duplicate would
        // silently shadow one of them.
        val duplicates = KeyboardMapping.entries.groupBy { it.name }.filter { it.value.size > 1 }
        assertTrue(duplicates.isEmpty(), "Duplicated names: ${duplicates.keys}")
    }

    @Test
    fun syntheticCodesDoNotCollideWithPrintableOnes() {
        // The whole reason synthetic codes start at 15: a key with no printable
        // character must not be confused with one that has.
        val printable = KeyboardMapping.entries.filter { it.sym == 0 }.map { it.key }
        val synthetic = KeyboardMapping.entries.filter { it.sym != 0 }.map { it.key }

        assertTrue(
            synthetic.all { it < KeyboardMapping.FIRST_SYNTHETIC_KEY_CODE + synthetic.size },
            "Synthetic codes ran past their block: $synthetic",
        )
        assertTrue(
            printable.none { it in synthetic },
            "A printable key shares a code with a synthetic one.",
        )
    }

    @Test
    fun theKeysInjectKeyAsksForAllExist() {
        // injectKey() maps characters onto these names. A missing one throws at
        // the moment the user types that character, which is a poor time to find
        // out.
        for (name in listOf("key_SPACE", "key_COLON", "key_QUOT", "key_SLASH", "key_ENTER")) {
            assertNotNull(KeyboardMapping.byName(name), "Missing '$name'.")
        }
        // injectKey() builds "key_$ch" for everything else, so the digits and
        // letters it will ask for have to be there too.
        for (ch in ('0'..'9') + ('A'..'Z')) {
            assertNotNull(KeyboardMapping.byName("key_$ch"), "Missing 'key_$ch'.")
        }
    }

    @Test
    fun labelsAreResolvedCharactersRatherThanEscapes() {
        // The XML spelled these as Android resource escapes; nothing should still
        // look like one.
        val unresolved = KeyboardMapping.entries.filter { "\\" in it.label }
        assertTrue(unresolved.isEmpty(), "Unresolved escapes in: ${unresolved.map { it.name }}")

        assertEquals("↑", KeyboardMapping.byName("key_UP")?.label)
        assertEquals("↓", KeyboardMapping.byName("key_DOWN")?.label)
        assertEquals("←", KeyboardMapping.byName("key_LEFT")?.label)
        assertEquals("→", KeyboardMapping.byName("key_RIGHT")?.label)
        assertEquals("@", KeyboardMapping.byName("key_AT")?.label)
        assertEquals("#", KeyboardMapping.byName("key_HASH")?.label)
        assertEquals("?", KeyboardMapping.byName("key_QUESTION")?.label)
    }

    @Test
    fun theSdlCodesForTheKeysWithoutCharactersAreUnchanged() {
        // Spot-checked against the XML the parser used to read, since these are
        // what the emulator core actually receives.
        assertEquals(13, KeyboardMapping.byName("key_ENTER")?.sym)
        assertEquals(12, KeyboardMapping.byName("key_CLEAR")?.sym)
        assertEquals(27, KeyboardMapping.byName("key_BREAK")?.sym)
        assertEquals(280, KeyboardMapping.byName("key_SHIFT_LEFT")?.sym)
        assertEquals(281, KeyboardMapping.byName("key_SHIFT_RIGHT")?.sym)
        assertEquals(273, KeyboardMapping.byName("key_UP")?.sym)
        assertEquals(274, KeyboardMapping.byName("key_DOWN")?.sym)
        assertEquals(8, KeyboardMapping.byName("key_LEFT")?.sym)
        assertEquals(9, KeyboardMapping.byName("key_RIGHT")?.sym)
    }

    @Test
    fun anUnknownNameIsNotFound() {
        assertNull(KeyboardMapping.byName("key_DOES_NOT_EXIST"))
    }
}
